# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "todo-app-tf-state-486778105981"
    dynamodb_table = "todo-app-terraform-locks"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
